# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Главная"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[main]]
identifier = "students"
name = "Студентам"
url = "/categories/студентам/"
[main.params]
icon = "school"
newtab = false

[[social]]
identifier = "Spar-Kaliningrad"
name = "Спар Калининград"
url = "https://spar-kaliningrad.ru/"
[social.params]
icon = "brand-safari"


[[social]]
identifier = "VK"
name = "Пономарёв Олег Борисович vk.com/olegponomarev39"
url = "https://vk.com/olegponomarev39"
[social.params]
icon = "brand-vk"


